#
# SameSameC Linux build script (Clang)
#
trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  CMAKE_POLICY_VERSION_MINIMUM: '3.5'
  # Setting these at the job level ensures CMake picks them up automatically
  CC: clang
  CXX: clang++
steps:
- checkout: self
  submodules: true
- script: |
    set -eux
    sudo apt -y update
    sudo apt install -y valgrind clang
  displayName: 'Install Dependencies'
  timeoutInMinutes: 60

- script: |
    set -eux
    WLA_INCLUDE="$PWD/ci/relax_wla_dx_warnings.cmake"
    cmake -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_C_FLAGS="-g -Wall -Wextra -Wuninitialized" \
          -G "Unix Makefiles"
    make
    cd wla-dx
    cmake -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
          -DCMAKE_PROJECT_INCLUDE="$WLA_INCLUDE" \
          -G "Unix Makefiles"
    make
    cd ..
  displayName: 'Build Debug (Clang)'
  timeoutInMinutes: 60

- script: |
    set -eux
    bash ./run_tests.sh
  displayName: 'Run Tests (Debug)'
  timeoutInMinutes: 60

- script: |
    set -eux
    WLA_INCLUDE="$PWD/ci/relax_wla_dx_warnings.cmake"
    cmake -G "Unix Makefiles" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_FLAGS="-g -Wall -Wextra -Wuninitialized"
    make
    cd wla-dx
    cmake -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
          -DCMAKE_PROJECT_INCLUDE="$WLA_INCLUDE" \
          -G "Unix Makefiles"
    make
    cd ..
  displayName: 'Build Release (Clang) with Debug Symbols'
  timeoutInMinutes: 60

- script: |
    set -eux
    bash ./run_tests.sh
  displayName: 'Run Tests (Release)'
  timeoutInMinutes: 60
- template: ci/publish-test-failure-artifacts.yml
